{{- if .Values.loadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lotus-gateway-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: lotus-gateway-app
    release: {{ .Release.Name }}
{{- with .Values.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
{{- with .Values.loadBalancer.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: LoadBalancer
  selector:
    app: lotus-gateway-app
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.rpc }}
      targetPort: 2346
      name: rpc
{{- end }}
