image:
  repository: coryschwartz/lotus-gateway
  pullPolicy: IfNotPresent
  tag: mainnet-1c62d7a40

prometheusOperatorServiceMonitor: true

ports:
  rpc: 2346

ingress:
  enabled: false
  class: nginx
  host: example.com

deployment:
  replicas: 1

secrets:
  jwt:
    enabled: false
    secretName: ""
    token_key: ""

lotus:
  fullnodeApiMultiaddr: "/dns/lotus-gateway-backend/tcp/1234"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

additionalLabels: {}
