image:
  repository: coryschwartz/lotus-gateway
  pullPolicy: IfNotPresent
  tag: mainnet-1c62d7a40

prometheusOperatorServiceMonitor: true

check:
  enabled: false
  schedule: "0/15 * * * *"
  checkService: true
  # pushGateway is a hostname and port for a pushGateway accessible over http
  # eg: prometheus-pushgateway.kube-system:9091
  pushGateway: ""
  # items is a list of additional endpoints to check
  # eg:
  # - "wss://api.chain.love"
  # - "https://api.chain.love"
  items: []

ports:
  rpc: 2346

ingress:
  enabled: false
  class: nginx
  host: example.com

loadBalancer:
  enabled: false
  rpcPort: 80

deployment:
  replicas: 1

secrets:
  jwt:
    enabled: false
    secretName: ""
    token_key: ""

lotus:
  fullnodeApiMultiaddr: "/dns/lotus-gateway-backend/tcp/1234"

# set additional environment variables on the lotus-gateway
# eg:
# gatewayEnvs:
# - name: GOLOG_LOG_FMT
#   value: json
gatewayEnvs: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

additionalLabels: {}
