# required:
# Your application. Replace with your own details.
application:
  name: "nginx-example"
  labels: []
  container:
    name: application
    image: "nginx"
    imagePullPolicy: IfNotPresent
    command: []
    args: []
    env: {}
    resources: {}
  secrets:
    - name: example-secret # helm will create this secret
      keys:
        password: extraspecial
      mount: /here
    - name: external-secret # a pre-existing secret
      external: true
      mount: /there
  configMaps: [] # same format as secrets
  service:
    enabled: true
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        name: http
  ingress:
    enabled: false
    class: nginx
    annotations: {}
    httpRules:
      - host: example.com
        path: /
        servicePort: http

# Wallets are added to the wallet secret.
# if you don't want to specify wallets in values.yaml,
# you can add them later by editing the secret.
# wallets:
#   - address: f3xxxyyy
#     exported: aabbccdd
wallets: []

# lotus configuration
lotus:
  image: filecoin/lotus:latest
  lite:
    enabled: false
    backend: wss://api.chain.love

# Do you want prometheus monitoring with prometheus-operator?
prometheus:
  serviceMonitor: false
  path: /metrics
  port: ""

deployment:
  replicas: 1
