---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dealbot-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: dealbot-controller
    release: {{ .Release.Name }}
{{- with .Values.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    app: dealbot-controller
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
      name: dealbot

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dealbot-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: dealbot-worker
    release: {{ .Release.Name }}
{{- with .Values.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    app: dealbot-worker
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
      name: dealbot
