{{ if .Values.controller.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dealbot-controller
  labels:
    app: dealbot-controller
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dealbot-controller
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: dealbot-controller
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      volumes: []
      containers:
      - name: dealbot-controller
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - containerPort: 9991
            name: metrics
          - containerPort: 8764
            name: dealbot
        args: ["controller"]
        env:
          - name: DEALBOT_LISTEN
            value: "0.0.0.0:5678"
          - name: DEALBOT_METRICS
            value: prometheus
          # - name: DEALBOT_IDENTITY_KEYPAIR
          #   value:
          {{ if .Values.controller.postgres.enabled }}
          - name: DEALBOT_PERSISTENCE_DRIVER
            value: postgres
          - name: PGHOST
            value: {{ .Values.postgres.teamid }}-{{ .Release.Name }}-controllerdb
          - name: PGPORT
            value: "8764"
          - name: PGUSER
            value: {{ .Values.postgres.user }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgres.user }}.{{.Values.postgres.teamid }}-{{ .Release.Name }}-controllerdb.credentials.postgresql.acid.zalan.do
                key: password
          - name: PGDATABASE
            value: {{ .Values.postgres.database }}
          {{ end }}
        resources:
{{ toYaml .Values.controller.resources | indent 10 }}
        volumeMounts: []
{{ end }}
{{ if .Values.daemon.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dealbot-daemon
  labels:
    app: dealbot-daemon
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}

spec:
  replicas: {{ .Values.daemon.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dealbot-daemon
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: dealbot-daemon
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.daemon.persistence.enabled }}
      volumes: []
      {{- end }}
      containers:
      - name: dealbot-daemon
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - containerPort: 9991
            name: metrics
          - containerPort: 8764
            name: dealbot
        args: ["daemon"]
        env:
        # - name: LOTUS_API_MULTIADDR
        #   value: {{ .Values.daemon.lotusAPI.lotusAPIMultiaddr }}
        # - name: LOTUS_API_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.daemon.lotusAPI.lotusAPITokenSecret }}
        #       key: jwt-ro-privs-token
        - name: FULLNODE_API_INFO
          value: "$(LOTUS_API_TOKEN):$(LOTUS_API_MULTIADDR)"
        - name: DEALBOT_DATA_DIRECTORY
          value: /data
        - name: DEALBOT_NODE_DATA_DIRECTORY
          value: /nodedata
        - name: DEALBOT_WALLET_ADDRESS
          value:
        - name: DEALBOT_LISTEN
          value: "0.0.0.0:8764"
        - name: DEALBOT_CONTROLLER_ENDPOINT
          value: {{ .Release.Name }}-controller
        {{- if .Values.daemon.persistence.enabled }}
        volumeMounts:
        - name: daemon-data
          mountPath: /data
        - name: daemon-node-data
          mountPath: /nodedata
        {{- end }}
        resources:
{{ toYaml .Values.daemon.resources | indent 10 }}
{{ end }}
