{{ if .Values.controller.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: dealbot-controller
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: dealbot-controller
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
      name: dealbot
    - protocol: TCP
      port: 8763
      targetPort: 8763
      name: dealbotgraphql
{{ end }}

{{ if .Values.daemon.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    app: dealbot-controller
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: dealbot-controller
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
      name: dealbot
{{ end }}
