{{- range $sec := .Values.application.secrets }}
{{- if not $sec.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $sec.name }}
data:
  {{ toYaml .keys | nindent 2 }}
{{- end }}
{{- end }}
