apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfsfiled.service-name-daemon-api" . }}
  labels:
    {{- include "ipfsfiled.allLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ipfsfiled.selectorLabels" . | nindent 4 }}
  ports:
    - name: api-port
      protocol: TCP
      port: 1234
