enabled: true

minerIDs:
  - t01000
  - t01001
  - t01002

# this is the service name of the lotus-seed install
lotusSeed: "localnet-seed-lotus-seed.default.svc.cluster.local"

image:
  lotusShed:
    # required binaries lotus, lotus-shed, lotus-seed
    repository: lotus-shed
    tag: 2k-2b0022f1a
    pullPolicy: IfNotPresent
  nginx:
    repository: nginxinc/nginx-unprivileged
    tag: mainline
    pullPolicy: IfNotPresent
  kubectl:
    repository: bitnami/kubectl
    tag: latest
    pullPolicy: IfNotPresent

persistence:
  enabled: true
  ## Filecoin data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  genesis:
    size: "5Gi"
    storageClassName: null
    accessModes:
      - ReadWriteOnce

nodeSelector: {}

tolerations: []

affinity: {}

service:
  # API service
  type: ClusterIP
  port: 80
  targetPort: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000
