apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-archiver.service-name-lily-api" . }}
  labels:
    {{- include "sentinel-archiver.allLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel-archiver.selectorLabels" . | nindent 4 }}
  ports:
    - name: api-port
      protocol: TCP
      port: 1234
