# Default values for fil-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
pgPoolSize: 45
# Name of a secret containing password, user, host, port and database keys for a postgres database
pgSecret: "sentinel-monitoring-postgresql-secrets"
logLevel: info
image:
  repo: filecoin/sentinel-visor
  tag: master-latest
  pullPolicy: IfNotPresent

# may add custom labels
# labels:
#   name: foo

# lotus api multiaddr
# if unset uses default value of:
# /dns/{{ .Release.Name }}-lotus-daemon.{{ .Release.Namespace }}.svc.cluster.local/tcp/1234
lotusAPIMultiaddr: ""
# a lotus-fullnode secret containing jwt token under key jwt-ro-privs-token
# secret must be in the same namespace
# if unset uses default value of:
# {{ .Release.Name }}-jwt-secrets
lotusAPITokenSecret: ""
# postgresql database
# if left empty, a database will be created with the following convention:
# <namespace>-<release>-sentinel
database: ""
# prometheus service monitor
prometheusOperatorServiceMonitor: false

#
# Args
#
allowAutomaticMigration: true

tasks:
  indexLatest:
    enabled: true
    cacheLength: 25
  indexHistory:
    enabled: true
  processTipSets:
    workers: 2
    batch: 10
    lease: "15m"
  processActors:
    workers: 2
    batch: 10
    lease: "15m"
#   includeActorType:
#   excludeActorType:
  processMessages:
    workers: 2
    batch: 10
    lease: "15m"
  processGasOutputs:
    workers: 2
    batch: 10
    lease: "15m"
  processChainEconomics:
    workers: 2
    batch: 10
    lease: "15m"
#  heightFrom: 0
#  heightTo: 100
  # Refresh frequency for processing stats
#  processingStatsRefresh: "1m"
  # Refresh frequency for chain visualization views
#  chainvisRefresh: "15m"
  # Base time to wait between starting tasks (jitter is added)
#  taskDelay: "500ms"
#
# Tracing
#
jaeger:
  enabled: false

resources:
  requests:
    cpu: 8000m
    memory: 32Gi
  limits:
    cpu: 16000m
    memory: 64Gi
