---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resolve
spec:
  schedule: {{ .Values.resolve.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: resolve
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: "{{ .Values.image.pullPolicy }}"
              command: [ "nebula" ]
              args: [ "resolve" ]
              env:
                {{- if .Values.postgres.enabled }}
                - name: NEBULA_DATABASE_HOST
                  value: {{ .Values.postgres.teamid }}-{{ .Release.Name }}-crawldb
                - name: NEBULA_DATABASE_PORT
                  value: "5432"
                - name: NEBULA_DATABASE_NAME
                  value: {{ .Values.postgres.database }}
                - name: NEBULA_DATABASE_USER
                  value: {{ .Values.postgres.user }}
                - name: NEBULA_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.user }}.{{.Values.postgres.teamid }}-{{ .Release.Name }}-crawldb.credentials.postgresql.acid.zalan.do
                      key: password
                - name: NEBULA_DATABASE_SSL
                  value: {{ .Values.postgres.ssl }}
                {{- end }}
                - name: NEBULA_RESOLVE_BATCH_SIZE
                  value: {{ quote .Values.resolve.config.batch }}

# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: report
# spec:
#   schedule: {{ .Values.report.schedule }}
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           restartPolicy: OnFailure
#           containers:
#             - name: report
#               image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#               imagePullPolicy: "{{ .Values.image.pullPolicy }}"
#               command: [ "?" ]
#               args: [ "?" ]
#               env:
#                 {{- if .Values.postgres.enabled }}
#                 - name: NEBULA_DATABASE_HOST
#                   value: {{ .Values.postgres.teamid }}-{{ .Release.Name }}-crawldb
#                 - name: NEBULA_DATABASE_PORT
#                   value: "5432"
#                 - name: NEBULA_DATABASE_NAME
#                   value: {{ .Values.postgres.database }}
#                 - name: NEBULA_DATABASE_USER
#                   value: {{ .Values.postgres.user }}
#                 - name: NEBULA_DATABASE_PASSWORD
#                   valueFrom:
#                     secretKeyRef:
#                       name: {{ .Values.postgres.user }}.{{.Values.postgres.teamid }}-{{ .Release.Name }}-crawldb.credentials.postgresql.acid.zalan.do
#                       key: password
#                 - name: NEBULA_DATABASE_SSL
#                   value: {{ .Values.postgres.ssl }}
#                 {{- end }}
